#!/usr/bin/env bash
# Install nginx web server and edit index.html file
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R $USER:$USER /var/www
chown -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
service nginx restart
