#!/usr/bin/env bash
# Install nginx web server and edit index.html file
apt-get -y update
apt-get -y install nginx
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
