#!/usr/bin/env bash
# Install nginx web server, edit index.html file and configure redirection
FILE="/etc/nginx/sites-available/default"
NEW_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
sed -i "/server_name _;/a\ \trewrite ^/redirect_me$ $NEW_URL permanent;" $FILE
service nginx restart
