#!/usr/bin/env bash
# Install nginx web server, edit index.html file and configure redirection
FILE="/etc/nginx/sites-available/default"
HOST_NAME=$(hostname)
REDIR_404=$(cat <<EOF
server {
	listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	error_page 404 /c_404.html;
	location / {
		add_header X-Served-By $HOST_NAME;
	}
	location = /c_404.html {
		root /usr/share/nginx/html;
		internal;
	}
}
EOF
)

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
mkdir -p /usr/share/nginx/html
echo -e "Ceci n'est pas une page\n" > /usr/share/nginx/html/c_404.html
echo "$REDIR_404" > "$FILE"
service nginx restart
