#!/usr/bin/env bash
# Install nginx web server, edit index.html file and configure redirection
FILE="/etc/haproxy/haproxy.cfg"
CONFIG_STR=$(cat <<EOF

listen web_servers
	bind *:80
	balance roundrobin
	server s1 54.160.125.191:80 check
	server s2 54.144.46.227:80 check

	http-request set-header X-Served-By %[req.hdr(X-Served-By)]
EOF
)

apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy
apt-get -y install haproxy
echo "$CONFIG_STR" >> "$FILE"
service haproxy restart
