#!/usr/bin/env bash
#Use while loop to print 10 time
#Use if condition to print Hi for the 9th iteration

i=1
while [ "$i" -le 10 ]; do
	echo "Best School"
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
