#!/usr/bin/env bash
# Install ufw for firewall management and update rules
apt-get update
apt-get install ufw
ufw allow 22
ufw allow 80
ufw allow 443
ufw default deny incoming
ufw default allow outgoing
ufw enable
