#!/bin/bash

# Get the list of network interfaces
interfaces=$(ifconfig -a | grep '^[a-zA-Z]' | awk -F':' '{print $1}')

# Loop through each interface and display its IPv4 addresses
for interface in $interfaces; do
    ipv4_addresses=$(ifconfig $interface | grep 'inet ' | awk '{print $2}')
    
    if [ -n "$ipv4_addresses" ]; then
        echo "$ipv4_addresses"
    fi
done
